spring.application.name=notification-service

server.port=${SERVER_PORT:8085}

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/notification_db
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID:notification-service}
spring.kafka.consumer.auto-offset-reset=earliest

# Topic consumed by this service
app.kafka.topics.loan-offer-generated=${LOAN_OFFER_GENERATED_TOPIC:loan.offer.generated}