spring.application.name=notification-service

server.port=${SERVER_PORT:8085}

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/notification_db
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID:notification-service}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties[spring.deserializer.value.delegate.class]=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

spring.kafka.consumer.properties[spring.json.value.default.type]=com.btproject.loanplatform.notification_service.infrastructure.messaging.in.LoanOfferGeneratedEvent
spring.kafka.consumer.properties[spring.json.trusted.packages]=com.btproject.loanplatform.notification_service.infrastructure.messaging.in
spring.kafka.consumer.properties[spring.json.use.type.headers]=false

# Producer used for DLQ publishing
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties[enable.idempotence]=true
spring.kafka.producer.properties[spring.json.add.type.headers]=false

# Topics
app.kafka.topics.loan-offer-generated=${LOAN_OFFER_GENERATED_TOPIC:loan.offer.generated}
app.kafka.topics.loan-offer-generated-dlq=${LOAN_OFFER_GENERATED_DLQ_TOPIC:loan.offer.generated.dlq}

# Customer Service client
app.clients.customer-service.base-url=${CUSTOMER_SERVICE_URL:http://localhost:8081}
app.clients.customer-service.username=${CUSTOMER_SERVICE_USERNAME:user}
app.clients.customer-service.password=${CUSTOMER_SERVICE_PASSWORD:user123}
app.clients.customer-service.connect-timeout=${CUSTOMER_SERVICE_CONNECT_TIMEOUT:2s}
app.clients.customer-service.read-timeout=${CUSTOMER_SERVICE_READ_TIMEOUT:3s}
app.clients.customer-service.retry.max-attempts=${CUSTOMER_SERVICE_MAX_ATTEMPTS:3}
app.clients.customer-service.retry.backoff=${CUSTOMER_SERVICE_RETRY_BACKOFF:500ms}
